### ISSUE TITLE
bug: Randomly Assigned a Different Task (from the same project) While Part way Through one.

### ISSUE THREAD

**Issue by Pseudorandom-Pseudonym** [mapswipe/mapswipe-web#21]
**Describe the bug**
The bug occurs at seemingly at random. When part way through a task: you are 'teleported' to part way through a different task. This new task has no contribution data i.e. if you go back through the previous tiles of the task, no tiles are marked with either yes, meybe or bad-imagery. I'm assuming that contribution data on the original task is also **not** saved.

**To Reproduce**
1. Contribute to a find type task (preferably one close to completion).
2. Complete the contribution, but do **not** save
3. Wait
4. See error (the screen should momentarily go blank and you will now be contributing to a different task)

**Expected behavior**
You should manually choose to start a new task, not be automatically assigned to a different one part way through contributing.

**Screenshots**
![Mapswipe4web Selection Glitch](https://github.com/mapswipe/mapswipe-web/assets/170571789/ff21249f-0a1c-40be-ad99-48299d1948c6)
Fig.1. Displays 18 squares selected (data from previous task) in the top right corner even though no squares are selected in the current task.
![Mapswipe4web Save Without Full Progress Glitch](https://github.com/mapswipe/mapswipe-web/assets/170571789/7a8da197-7c42-4b5c-8b3c-96e2777c1899)
Fig.2. Allows you to save and end the task part way through.

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Firefox]
 - Version [126]

**Additional context**
The bug can occur multiple times during contribution at various time intervals.

The tiles selected display contains data from a previous task(s), and can overflow i.e. display natural numbers 18<X. Clicking the unselect all tiles button resets it to 0. REF: Fig.1.

The task allows you to save and exit part way throught a task even when you have not interacted with it in any way. REF: Fig.2.

Unsure: The bug seems to occur on find type tasks close to completion.

**Comment by Pseudorandom-Pseudonym** [comment]
It occured before the deployment of version 0.1.3, and after you [mentioned https://github.com/mapswipe/mapswipe-web/commit/11e399ee8d1ebf421def99189792a198de213703 ](https://github.com/mapswipe/mapswipe-web/issues/14#issuecomment-2135591476) deploying with version 0.1.2

**Comment by ofr1tz** [comment]
Thanks for the clarification. While the mentioned commit prevented getting a seemingly random blank screen (#14) on Find projects, it unfortunately did not tackle the underlying problem, leading to the bug that you describe. This, however, should be fixed now with version 0.1.3.
