### ISSUE TITLE
Bug? I am Able to Save my Contributions while the Green Progress bar is not Full (if it Previously was)

### ISSUE THREAD

**Issue by Pseudorandom-Pseudonym** [mapswipe/mapswipe-web#24]
**Describe the bug**
If I go to the end of a task, then I am able to save my contributions without the green bar at the bottom being full.

**To Reproduce**
1. Contribute to a (find or validate type) project.
2. Fill the progress bar completley by getting to the end of a task group.
3. The save icon will now be clickable
4. If you go back (to the left) through the set to previous tasks the save icon will remain clickable

**Previous behavior**
Previously you would not be able to save unless you were at the end of a task group.

**Screenshots**
![Standatrd Full Size Window View Plus Saving Before Completion 'Bug'](https://github.com/mapswipe/mapswipe-web/assets/170571789/2f0d4caa-bb34-41bb-a4a8-e30a267c3a03)
Fig.1. Saving possible while Green bar not Full

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Firefox]
 - Version [127.0.1]

**Additional context**
The reason I added "Bug?" to the title is because this could be a useful feature, and *may not necessarily need to be fixed*. In fact this bug report could quite easily be changed to a feature request.

I think that this functionality is desirable, becuase it enables mappers to go back through a task group and check/correct previous tasks without being additionally penalised for it, by having to take the extra time to go back to the end of the task group, to only then be able to save their contributions. This could have a positive impact on the quality of data contributed thorugh mapswipe. It *may* also be a good idea to add some kind of 'are you sure?' pop-up when saving to prevent miss-clicks, or *maybe* move the save button elsewhere, although this comes with its own minor drawbacks to contribution rate, and I don't think I've personally miss-clicked with the current format. 

The website behaves like this since at least post relase [v0.1.4](https://github.com/mapswipe/mapswipe-web/releases/tag/v0.1.4)

**Comment by ofr1tz** [comment]
This is indeed the intended behavior. 

We want to make sure that the user has had a chance to see all tasks before being able to submit results. Once the end of the task group is reached, the user is free to check on previous task while able to submit results at any moment.
