### ISSUE TITLE
Bug - can't scroll after navigating to next screen

### ISSUE THREAD

**Issue by jhenshall** [mapswipe/mapswipe-web#3]
On the first screen of a project I can scroll up and down to see the full length of the squares. After I click to load the next batch, the scroll doesn't work. Screen recording below but to note: at the end, you can't see that I'm attempting to scroll.

Possible suggestion - to resize the boxes to fit the screen so that scrolling not required? But not sure how this would work in practice with all the different screen sizes.

https://github.com/mapswipe/mapswipe-web/assets/6359748/7641fb49-8d63-458e-9065-da70e17b0ec4

**Comment by petya-kangalova** [comment]
We just did some testing and experienced the same issue using Edge and Chrome. 
![Move next - mapswipe](https://github.com/mapswipe/mapswipe-web/assets/98902727/91c56710-c422-4949-a08d-4bddd7f71aec)

Two users used Firefox and did no encounter the issue. Could be browser related.

**Comment by ofr1tz** [comment]
Thanks, we do indeed encounter the issue as well. We are on it and will provide a fix with the next release.
