### ISSUE TITLE
Resizing to different window size

### ISSUE THREAD

**Issue by jhenshall** [mapswipe/mapswipe-web#4]
When resizing the browser window, the squares reposition out of order. Two examples below. Perhaps better to enforce the 6x3 grid that just gets smaller - not ideal for UX but does enforce the benefit of using a wider landscape window size.

<img width="300" alt="Screenshot 2024-04-23 at 16 42 14" src="https://github.com/mapswipe/mapswipe-web/assets/6359748/edafed78-b77f-418f-bbbf-4c162c414f27">

<img width="300" alt="Screenshot 2024-04-23 at 16 41 52" src="https://github.com/mapswipe/mapswipe-web/assets/6359748/6d262a15-3c36-4b5f-ad4b-cfa6106000b4">

**Comment by ofr1tz** [comment]
Hi, thanks for posting the issue!

Could you please indicate which browser/OS this occured on?

**Comment by jhenshall** [comment]
Hi, sorry for the delay. It was on MacOS 14.4.1 and Chrome 124.0.6367.62.

**Comment by ofr1tz** [comment]
Thanks! We could not reproduce this issue, does it persist on your side?

The expected behaviour is that the number of "columns" of image tiles adapts to window size/aspect ratio. There should always be 3 lines of image tiles, however.

**Comment by Pseudorandom-Pseudonym** [comment]
@ofr1tz the issuse persists, though not in quite the same way as shown in the original bug report of this issue. Really I'm not sure whether to open a new report and refer to it here, or to produce a new bug report in the comments of this one. What are your thoughts? I'll submit my findings later with images etc.
