### ISSUE TITLE
Find - The third page (Tutorial tab) heading looks different than that of Figma

### ISSUE THREAD

**Issue by kopitek8** [mapswipe/mapswipe-web#40]
## Dev Version Screenshot
![Image](https://github.com/user-attachments/assets/a94dd135-966b-4437-b49e-38c88ad63490)

## Figma Screenshot
![Image](https://github.com/user-attachments/assets/9ca54a4d-0e00-43b3-ba19-01e939295e72)

## Figma Design Link

https://www.figma.com/design/zm8eLul43iSJo95rdFWgGL/Mapswipe-Web-App?node-id=65-642&t=h9FUBsYyj3yrNCqD-4

**Comment by ofr1tz** [comment]
The page from the Figma screenshot is the one you would find under the "What to look for" tab in the dev version, so on page 1. In the mobile app, the information pages (here: "What to look for") come before the tutorial as well, so I'd propose to have the same order. I would however propose to move the "How to contribute" tab in the first position, so the order would be:

How to contribute > Information page(s) with their respective titles > Tutorial

**Comment by tnagorra** [comment]
@kopitek8 Let's update the mockup to reflect this change.
