### ISSUE TITLE
Last two pages are missing before the mapping page

### ISSUE THREAD

**Issue by kopitek8** [mapswipe/mapswipe-web#41]
## Issue
After the user completes the tutorial, the user is directly navigated to the start mapping page and two pages are missing

## Missing Figma Designs
![Image](https://github.com/user-attachments/assets/64a92666-a43f-4e74-8775-ac776db21caa)

![Image](https://github.com/user-attachments/assets/83d02906-b50b-478c-b0f5-c2b8eb4ed355)

**Comment by ofr1tz** [comment]
I would suggest to integrate the first of the two missing pages ("Don't worry...") into the "How to contribute" (instructions) page where it would fit well.

I also find, however, that the second missing page ("You're ready to start...") would be helpful. At the moment, just a "Start Mapping" appears.

**Comment by tnagorra** [comment]
@ofr1tz should we edit the 'How to contribute' to add the "don't worry" text? Also, is this the case for all the project types?

@ofr1tz do you mean to add a page/view after the last tutorial page with "you are ready to start mapswiping" text?

**Comment by ofr1tz** [comment]
#tnagorra I can push a commit for the first part myself. In all project types, we collect results from several users per task. The number depends on verificationNumber in the project entry.

For the "ready to start mapping" page, I would not suggest to add this as another tab. But for better visibility, the content of that page could maybe replace the tile grid on the tutorial grid, once all tutorial pages are completed.

**Comment by tnagorra** [comment]
Thanks @ofr1tz that would be helpful.

The idea is to not add a new "tab" but after the completion of the tutorial, the contents will be replaced by the message "you are ready to ..." and a "start mapping" button.
