### ISSUE TITLE
Validate - Buttons not as per Figma design

### ISSUE THREAD

**Issue by kopitek8** [mapswipe/mapswipe-web#42]
## Issue Screenshot

<img width="1016" alt="image" src="https://github.com/user-attachments/assets/fb040111-3d2e-47c2-815c-8334ff0df0d9">

## Figma Screenshot

<img width="675" alt="image" src="https://github.com/user-attachments/assets/54fb90a4-8c17-45e5-998d-5879bee80e84">

## Figma Design Link

https://www.figma.com/design/zm8eLul43iSJo95rdFWgGL/Mapswipe-Web-App?node-id=37-1589&t=h9FUBsYyj3yrNCqD-4

**Comment by ofr1tz** [comment]
The labels, icons, colors and the order and number of buttons for validate projects can be customized, so this may divert from the Figma design based on how the answer options were defined when the tutorial was created with the Manager Dashboard.

I agree that the overall design of the option buttons could be improved (more similar to the design in the Figma Screenshot). As this would  need to be implemented not only for the tutorial, but in the same way for the project itself, I would however rather open an issue for the MapSwipe web app in general and not make this part of the tutorials implementation.

**Comment by tnagorra** [comment]
@kopitek8 let's move this issue outside of the "Mapswipe Web Tutorials" project.

**Comment by kopitek8** [comment]
This issue has been moved outside the 'MapSwipe Web Tutorials' project board and is now a global issue for the whole repository.

**Comment by ofr1tz** [comment]
Closing this here, as there is a new issue #51 covering this.
