### ISSUE TITLE
Z - Index issues

### ISSUE THREAD

**Issue by kopitek8** [mapswipe/mapswipe-web#43]
## Description 
In the tutorial of the web app the overlays (yes, maybe, bad imagery, and no) cover the options to zoom the tile and the option to enable the border.

## Steps to Replicate 
 - Go to the tutorials of the web app 
 - Click on the middle of the tile 
 - Try to click on the zoom/border enable button 

## Expected Outcome 
The overlay should not cover the options 

## Actual Outcome 
The overlay covers the options 
<img width="413" alt="Screenshot 2024-09-30 at 2 53 23 PM" src="https://github.com/user-attachments/assets/f4c9c75b-0739-449f-8499-83114eb2cd18">

**Comment by Shhhhhubh** [comment]
## Description 
In the tutorial of the web app the overlays (yes, maybe, bad imagery, and no) cover the options to zoom the tile and the option to enable the border.


## Steps to Replicate 
 - Go to the tutorials of the web app 
 - Click on the middle of the tile 
 - Try to click on the zoom / border enable button

**Comment by tnagorra** [comment]
@kopitek8 this is a regression from the previous behavior.
