### ISSUE TITLE
Validate - Visibility icon not present in mapping pages

### ISSUE THREAD

**Issue by kopitek8** [mapswipe/mapswipe-web#44]
## Issue
The visibility button is not present on the Web App but the Visibility page is present in the Mob App but not in web app

## Screenshot
![Image](https://github.com/user-attachments/assets/a8204902-2d39-4bc7-b002-ef62315308c5)

**Comment by tnagorra** [comment]
The visibility button is implemented for the project so, we might not need these just for tutorial.

**Comment by ofr1tz** [comment]
Apart from the visibility button, there's also the reset view button missing. Both are part of the toolbar on top of the actual mapping component.

Both buttons are explained on the instructions page. I guess we can do without them on the interactive tutorial?
