### ISSUE TITLE
Rename "Swipe" to something different in tutorials page

### ISSUE THREAD

**Issue by kopitek8** [mapswipe/mapswipe-web#45]
From Nicole:

The language of "swipe" does not work so well for the web app, since one is not really swiping when moving forward.

![Image](https://github.com/user-attachments/assets/26290836-b0fd-47e1-ae02-429c08f773e4)

I might say something like "keep scrolling", or "press the right arrow key."

In this case of this tutorial, because there is no other way to move forward other than to click on "next task", you might want to mention this as well. Or, find a way to move forward how you would like them to move if they were actually mapping and then at the bottom you could say, "click on next task to continue."

**Comment by ofr1tz** [comment]
This is a tricky one, as the content of the message displayed comes from the tutorial in Firebase. On a general level, I am afraid the only sustainable fix for this is to change the tutorials themselves wherever there are currently references to swiping, tapping etc.

**Comment by ofr1tz** [comment]
Here is a related example which is quite unfortunate:

![Image](https://github.com/user-attachments/assets/376338ca-eb07-4b41-a593-444f68284f0f)

In the mobile app, you can swipe to indicate there is no change in a project of type Compare. However, in the web app, one needs to actively click the "No" answer button. The instructions does not fit here, but the only way to fix this is probably adapting the tutorial content?

**Comment by tnagorra** [comment]
Agree with @ofr1tz 
The tutorial content is the same across web app and mobile app but the UI and interactions are different.
