### ISSUE TITLE
Make the first page a dynamic variable

### ISSUE THREAD

**Issue by kopitek8** [mapswipe/mapswipe-web#46]
From Nicole

In the find buildings tutorial, the first page says "Please look for them.", which is pretty unclear. It might be helpful to make "them" a variable that will change depending on what the project creator sets to be looked for in the project settings. Then this would update automatically.

![Image](https://github.com/user-attachments/assets/048de100-3767-481c-aebe-e5e8b636f2e2)

**Comment by ofr1tz** [comment]
This is actually dynamic. The entire content of this page (or: potentially several pages) comes from Firebase, based on the tutorial created through the Manager Dashboard.

The specific content in the screenshot is from a tutorial on the MapSwipe dev instance that was probably created for testing purposes only, not for providing meaningful information.

**Comment by ofr1tz** [comment]
Agreed, closing this.
