### ISSUE TITLE
Validate - No offset button and 'Not sure' button unreadable

### ISSUE THREAD

**Issue by kopitek8** [mapswipe/mapswipe-web#47]
From Nicole:

For the validate project type, there is no offset button, and the text at the bottom of the screen is very small and the yellow is almost impossible to read.

![Image](https://github.com/user-attachments/assets/900eee55-195a-4b86-a7d6-4b6b96632342)

**Comment by tnagorra** [comment]
The color selection for "Not sure" button can be configured while creating the tutorial.

Is "No offset button" the same issue as discussed in https://mapswipe.slack.com/archives/C0HCW2CJJ/p1727778601774099 ? Should we close this?
