### ISSUE TITLE
An extra g in GmbH

### ISSUE THREAD

**Issue by nicolelaine** [mapswipe/mapswipe-web#7]
**Describe the bug**
There is an extra g in GmbH in the footer

**Screenshots**

<img width="1334" alt="Screenshot 2024-04-29 at 15 07 19" src="https://github.com/mapswipe/mapswipe-web/assets/15011784/cb01f946-f5cb-4eef-8c9c-d2e9541661d0">

**Comment by ofr1tz** [comment]
Hi Nicole, this is intentional -- HeiGIT is a "gemeinnützige" (non-profit) GmbH, abbreviated as gGmbH.
